// The grimoire: every card Whimsy can draw.
//
// Fields
//   id        stable identifier (never reuse or rename; ratings and bans point at it)
//   mode      'stuck' (Get unstuck) or 'bored' (Surprise me)
//   cats      stuck only: categories it suits, or ['any']
//   snags     stuck only: blockages it helps with, or ['any']
//   intents   bored only: make | explore | reset | play ('play' cards appear under Anything)
//   flavor    the kind of move (see FLAVORS)
//   family    cards with the same family count as the same idea for repetition control
//   weird     1 Nudge, 2 Twist, 3 Absurd
//   effort    1 light, 2 some, 3 full
//   mins      suggested minutes (also the minimum time it needs)
//   where     settings it works in: desk, home, out
//   needs     outside, move, talk, sound, camera (comfort rules can block these)
//   title, action, boundary, finish, bridge   card text; {tokens} are World Dice
//   adapt     variants: smaller, indoors, still, quiet, nocam, weirder. Each overrides fields of
//             the original. Variants inherit finish and bridge, but not boundary.

const ALL = ['desk', 'home', 'out'];
const INSIDE = ['desk', 'home'];
const MOBILE = ['home', 'out'];

const stuck = (o) => ({ mode: 'stuck', where: ALL, needs: [], effort: 1, weird: 1, ...o });
const bored = (o) => ({ mode: 'bored', where: ALL, needs: [], effort: 1, weird: 1, ...o });

export const DECK = [
  // ───────────────────────── Get unstuck: works for any category ─────────────────────────
  stuck({
    id: 'u-ten-year-old', cats: ['any'], snags: ['unsure', 'start', 'options'], flavor: 'reframe', family: 'explain-simply',
    weird: 1, effort: 1, mins: 5,
    title: 'The ten-year-old test',
    action: 'Describe the problem in one sentence a ten-year-old would understand. No jargon allowed.',
    boundary: 'One sentence. If it runs long, cut it in half.',
    finish: 'You have a sentence you could say out loud without explaining it.',
    bridge: 'Put that sentence at the top of your work. It is your compass now.',
    adapt: {
      smaller: { action: 'Name the problem in five words or fewer.', mins: 2, finish: 'Five words or fewer, written down.' },
      weirder: { action: "Explain the problem as a bedtime story for a ten-year-old. Start with 'Once upon a time'.", weird: 2, finish: 'A short bedtime story with a beginning, middle and end.' },
    },
  }),
  stuck({
    id: 'u-ten-terrible', cats: ['any'], snags: ['options', 'angle', 'start'], flavor: 'invert', family: 'bad-ideas',
    weird: 2, effort: 2, mins: 10,
    title: 'Ten terrible ideas',
    action: 'List ten deliberately terrible solutions. Then find the one good idea hiding inside the worst of them.',
    boundary: "Ten ideas, one line each. Don't fix them while you write.",
    finish: "You've circled one useful scrap from a bad idea.",
    bridge: 'Try that scrap on the real problem for five minutes.',
    adapt: {
      smaller: { action: 'List three terrible solutions and steal one detail from the worst.', mins: 5, effort: 1 },
      weirder: { action: 'List ten solutions a cartoon villain would use. Find the one that is secretly kind.', weird: 3 },
    },
  }),
  stuck({
    id: 'u-opposite-day', cats: ['any'], snags: ['angle', 'broken'], flavor: 'invert', family: 'do-opposite',
    weird: 2, effort: 2, mins: 10,
    title: 'Opposite day',
    action: "On scratch paper, sketch the exact opposite of your current approach. If you're adding, remove. If you're going fast, go slow.",
    boundary: 'Scratch copy only. Your real work stays untouched.',
    finish: 'You have one opposite version, however rough.',
    bridge: "Take one detail from the opposite back to the real thing. You don't have to keep the rest.",
    adapt: {
      smaller: { action: 'Write one sentence describing the exact opposite of your current approach.', mins: 3, effort: 1, finish: 'One opposite sentence.' },
    },
  }),
  stuck({
    id: 'u-ugly-first', cats: ['any'], snags: ['start'], flavor: 'squeeze', family: 'ugly-first',
    weird: 1, effort: 1, mins: 5,
    title: 'Ugly first draft',
    action: 'Spend five minutes making the ugliest, sloppiest possible version. Quality is banned.',
    finish: "Something exists that didn't before.",
    bridge: 'Now improve just one part of it.',
    adapt: {
      smaller: { action: 'Make the ugliest possible version of just the first step.', mins: 2 },
      weirder: { action: 'Make the ugly version while narrating it like a cooking show host.', weird: 2, needs: ['talk'] },
    },
  }),
  stuck({
    id: 'u-commentator', cats: ['any'], snags: ['broken', 'unsure'], flavor: 'perspective', family: 'explain-aloud',
    weird: 3, effort: 1, mins: 5, needs: ['talk'],
    title: 'Live commentary',
    action: 'Explain the problem out loud to a household object, in the voice of a sports commentator. Dramatic pauses encouraged.',
    boundary: 'Start from the beginning. Explain every step, even the obvious ones.',
    finish: "You've narrated the whole thing, or spotted the problem mid-sentence.",
    bridge: 'Write down the exact moment your commentary stumbled. That is where to look.',
    adapt: {
      quiet: { action: 'Write the play-by-play of the problem the way a sports commentator would. Every step, even the obvious ones.', needs: [] },
      smaller: { action: 'Commentate just the last step that went wrong, out loud.', mins: 2 },
    },
  }),
  stuck({
    id: 'u-two-minute-door', cats: ['any'], snags: ['start', 'finish'], flavor: 'squeeze', family: 'tiny-step',
    weird: 1, effort: 1, mins: 2,
    title: 'The two-minute door',
    action: "Do only the very first physical action. Open the file. Write the title. Pick up the pen. That's all.",
    finish: 'The first action is done.',
    bridge: "If you want to keep going, keep going. If not, you've still started.",
    adapt: {
      weirder: { action: 'Do only the very first physical action, using your non-dominant hand.', weird: 2 },
    },
  }),
  stuck({
    id: 'u-half-the-list', cats: ['any'], snags: ['options', 'finish'], flavor: 'subtract', family: 'cut-half',
    weird: 2, effort: 2, mins: 10,
    title: 'Half the list',
    action: "Write down everything you're juggling for this task. Cross out half. Nothing stays unless you can defend it in one sentence.",
    finish: 'Half the list is crossed out.',
    bridge: 'Work only on what survived. The rest can wait or disappear.',
    adapt: {
      smaller: { action: "Cross out just one thing you're juggling that doesn't really matter.", mins: 3, effort: 1, finish: 'One thing crossed out.' },
    },
  }),
  stuck({
    id: 'u-note-from-next-month', cats: ['any'], snags: ['unsure', 'options'], flavor: 'perspective', family: 'future-self',
    weird: 2, effort: 1, mins: 5,
    title: 'Note from next month',
    action: 'Write a three-line note from yourself one month from now, telling you what to do about this.',
    finish: 'Three lines written.',
    bridge: 'Do the first thing future-you suggested.',
    adapt: {
      weirder: { action: 'Write a three-line note from yourself in the year 2099, who finds this problem adorably small.', weird: 3 },
    },
  }),
  stuck({
    id: 'u-only-questions', cats: ['any'], snags: ['unsure', 'angle'], flavor: 'reframe', family: 'questions',
    weird: 1, effort: 2, mins: 10,
    title: 'Only questions',
    action: 'Write fifteen questions about the problem. No answers allowed.',
    finish: 'Fifteen questions, or one that makes you sit up.',
    bridge: 'Pick the most uncomfortable question and answer it first.',
    adapt: {
      smaller: { action: 'Write five questions about the problem. No answers allowed.', mins: 3, effort: 1, finish: 'Five questions.' },
      weirder: { action: 'Interview the problem out loud, talk-show style. Ask it five questions and answer as the problem.', weird: 3, needs: ['talk'], finish: 'Five questions asked and answered.' },
    },
  }),
  stuck({
    id: 'u-change-spot', cats: ['any'], snags: ['start', 'angle', 'unsure'], flavor: 'body', family: 'change-place',
    weird: 1, effort: 1, mins: 5, needs: ['move'],
    title: 'Change your spot',
    action: 'Move somewhere you never work, even just a different chair. Look at the problem from there.',
    finish: "You're somewhere new with the problem in front of you.",
    bridge: 'Write the first thought you have in the new spot.',
    adapt: {
      still: { action: 'Without getting up, turn your chair or screen to face a different direction. Look at the problem from there.', needs: [] },
    },
  }),
  stuck({
    id: 'u-walk-one-question', cats: ['any'], snags: ['angle', 'options', 'unsure'], flavor: 'body', family: 'walk-think',
    weird: 1, effort: 2, mins: 15, needs: ['move', 'outside'], where: MOBILE,
    title: 'Walk with one question',
    action: "Take a short walk with a single question in mind. Only look at your phone to note answers.",
    boundary: 'Up to fifteen minutes, on a route you know.',
    finish: "You've walked and noted at least one thought.",
    bridge: 'Back at your work, try the first idea you noted.',
    adapt: {
      indoors: { action: 'Walk slow laps around the room or building with a single question in mind. Note any answer that shows up.', needs: ['move'], where: INSIDE, mins: 10 },
      smaller: { action: 'Walk to the farthest room you can reach and back, holding one question in mind.', mins: 5, effort: 1, needs: ['move'], where: ALL },
    },
  }),
  stuck({
    id: 'u-three-moves', cats: ['any'], snags: ['options', 'finish'], flavor: 'subtract', family: 'limit-moves',
    weird: 2, effort: 2, mins: 15,
    title: 'Three moves only',
    action: "You're allowed exactly three changes to finish this. Choose them carefully, then make them.",
    finish: 'Three changes made.',
    bridge: "Look again. If it's good enough, call it done.",
    adapt: {
      smaller: { action: "Choose the single change that would matter most, and make only that one.", mins: 5, effort: 1, finish: 'One change made.' },
    },
  }),
  stuck({
    id: 'u-word-oracle', cats: ['any'], snags: ['angle', 'start'], flavor: 'dice', family: 'random-word',
    weird: 2, effort: 1, mins: 5,
    title: 'The word oracle',
    action: 'Your word is {word}. Find three ways it connects to your problem, however much of a stretch.',
    finish: 'Three connections written.',
    bridge: 'Use the least obvious connection as your starting point.',
    adapt: {
      weirder: { action: 'Your word is {word}. Rebuild your whole approach as if everything were made of it.', weird: 3, finish: 'One rebuilt approach, sketched roughly.' },
      smaller: { action: 'Your word is {word}. Find one way it connects to your problem.', mins: 2, finish: 'One connection written.' },
    },
  }),
  stuck({
    id: 'u-define-done', cats: ['any'], snags: ['finish'], flavor: 'reframe', family: 'define-done',
    weird: 1, effort: 1, mins: 5,
    title: 'Define done',
    action: "Write down exactly what 'finished' looks like for this. Three bullet points, no more.",
    finish: "You can tell, objectively, when you'll be done.",
    bridge: 'Do the smallest thing that ticks one bullet.',
  }),
  stuck({
    id: 'u-pretend-deadline', cats: ['any'], snags: ['finish', 'options'], flavor: 'squeeze', family: 'deadline-now',
    weird: 2, effort: 2, mins: 15,
    title: 'The pretend deadline',
    action: 'Pretend this is due in fifteen minutes with no extensions. Cut whatever you must to make it.',
    finish: 'You have a version you could hand over.',
    bridge: 'Decide honestly whether anything you cut needs to come back.',
    adapt: {
      smaller: { action: "Pretend it's due in five minutes. Write down the three things you'd drop.", mins: 5, effort: 1, finish: 'Three things on the drop list.' },
    },
  }),
  stuck({
    id: 'u-clock-decides', cats: ['any'], snags: ['options'], flavor: 'dice', family: 'clock-limit',
    weird: 2, effort: 1, mins: 5,
    title: 'The clock decides',
    action: 'The clock says {few}. Keep only {few} of your options. Choose now, no appeals.',
    finish: 'Only {few} left on the page.',
    bridge: 'Work with what is left. You can revisit tomorrow, not today.',
  }),
  stuck({
    id: 'u-message-friend', cats: ['any'], snags: ['unsure', 'broken'], flavor: 'perspective', family: 'outsider',
    weird: 1, effort: 1, mins: 5,
    title: 'Message to a friend',
    action: "Write a message asking a smart friend for help with this. Be specific. You don't have to send it.",
    finish: 'The message is written.',
    bridge: 'Read it back. The answer often hides in how you asked.',
  }),
  stuck({
    id: 'u-borrowed-expertise', cats: ['any'], snags: ['angle', 'options'], flavor: 'perspective', family: 'stranger-hat',
    weird: 3, effort: 1, mins: 5,
    title: 'Borrowed expertise',
    action: 'Solve this the way {role} would. What tools, habits and tricks would they bring?',
    finish: 'One idea in their style, written down.',
    bridge: 'Translate their idea back into your world. What survives?',
  }),
  stuck({
    id: 'u-problem-haiku', cats: ['any'], snags: ['unsure', 'angle'], flavor: 'reframe', family: 'compress-poem',
    weird: 3, effort: 1, mins: 5,
    title: 'Problem haiku',
    action: 'Describe the problem as a haiku: five syllables, then seven, then five.',
    finish: 'Three lines, syllables counted.',
    bridge: 'Which word did you fight hardest to fit? It is probably the heart of the problem.',
  }),
  stuck({
    id: 'u-no-inputs', cats: ['any'], snags: ['options', 'angle'], flavor: 'subtract', family: 'no-input',
    weird: 2, effort: 1, mins: 15,
    title: 'No inputs',
    action: "No tabs, no searches, no other people's notes. Work only from what's already in your head.",
    boundary: 'Fifteen minutes.',
    finish: "You've worked from memory alone until the time ran out.",
    bridge: "Compare what you made with what you'd have looked up. Keep what's yours.",
    adapt: {
      smaller: { action: "For five minutes: no tabs, no searches. Write down what you already know about the problem.", mins: 5 },
    },
  }),

  stuck({
    id: 'u-wrong-tool', cats: ['any'], snags: ['start', 'angle'], flavor: 'substitute', family: 'wrong-tool',
    weird: 3, effort: 1, mins: 5,
    title: 'Wrong tool first',
    action: 'Begin the task in a tool you would never use for it: plan code in a drawing app, design in a text editor, write in a spreadsheet.',
    finish: 'Something has started, in the wrong place.',
    bridge: 'Switch back to your usual tool. You are no longer starting from nothing.',
  }),
  stuck({
    id: 'u-opening-ceremony', cats: ['any'], snags: ['start'], flavor: 'reframe', family: 'ceremony',
    weird: 3, effort: 1, mins: 2, needs: ['talk'],
    title: 'Opening ceremony',
    action: 'Hold a tiny opening ceremony for this task. Announce it out loud, cut an imaginary ribbon, then work for ten seconds.',
    finish: 'The ribbon is cut and ten seconds of work are done.',
    bridge: 'Keep going while the applause lasts.',
    adapt: {
      quiet: { action: 'Write a one-line announcement for this task, cut an imaginary ribbon with two fingers, then work for ten seconds.', needs: [] },
    },
  }),
  stuck({
    id: 'u-acceptance-speech', cats: ['any'], snags: ['finish', 'start'], flavor: 'perspective', family: 'award-speech',
    weird: 3, effort: 1, mins: 5,
    title: 'The acceptance speech',
    action: 'Write your acceptance speech for finishing this. Thank the people, tools and snacks that got you there.',
    finish: 'A short, grateful, slightly ridiculous speech.',
    bridge: 'Do the one thing standing between you and giving that speech for real.',
  }),
  stuck({
    id: 'u-auction-listing', cats: ['any'], snags: ['finish', 'unsure'], flavor: 'reframe', family: 'auction',
    weird: 3, effort: 1, mins: 5,
    title: 'Auction listing',
    action: 'Write an auction listing for your work exactly as it is right now. Be honest about every flaw.',
    finish: 'A listing with an honest list of flaws.',
    bridge: 'Fix the flaw you were most embarrassed to list. The rest may be fine to ship.',
  }),
  stuck({
    id: 'u-noir-detective', cats: ['any'], snags: ['broken', 'unsure'], flavor: 'perspective', family: 'detective',
    weird: 3, effort: 1, mins: 10,
    title: 'Case notes',
    action: "Write a hard-boiled detective's case notes on the problem: the suspects, their alibis, and the one clue nobody checked.",
    finish: 'Suspects listed and one unchecked clue named.',
    bridge: 'Go and check that clue.',
    adapt: {
      smaller: { action: 'Name your top suspect for what is wrong, and the one clue nobody has checked.', mins: 3, finish: 'One suspect, one clue.' },
    },
  }),

  // ───────────────────────── Get unstuck: Code ─────────────────────────
  stuck({
    id: 'c-shrink-crime-scene', cats: ['code'], snags: ['broken'], flavor: 'subtract', family: 'smallest-repro',
    weird: 1, effort: 2, mins: 15, where: INSIDE,
    title: 'Shrink the crime scene',
    action: 'Find the smallest input, or the fewest lines, that still reproduce the problem. Delete everything else.',
    boundary: 'On a scratch copy or branch only.',
    finish: "You can't remove anything more without the bug disappearing.",
    bridge: 'The last thing you removed before it vanished is your prime suspect.',
    adapt: {
      smaller: { action: 'For five minutes, remove one thing at a time. Note which removal changes the behavior.', mins: 5, effort: 1, finish: 'A short list of removals and what each changed.' },
    },
  }),
  stuck({
    id: 'c-happy-ending', cats: ['code'], snags: ['start'], flavor: 'invert', family: 'usage-first',
    weird: 1, effort: 1, mins: 10, where: INSIDE,
    title: 'Write the happy ending first',
    action: 'Write the code that would use your finished feature, as if it already existed. Ignore how it works inside.',
    finish: 'A few lines showing how you wish it worked.',
    bridge: 'Now build backwards until those lines run.',
    adapt: {
      smaller: { action: 'Write one line that calls the finished feature, exactly how you wish it looked.', mins: 3, finish: 'One wishful line.' },
    },
  }),
  stuck({
    id: 'c-one-failing-test', cats: ['code'], snags: ['start', 'broken'], flavor: 'squeeze', family: 'test-first',
    weird: 1, effort: 2, mins: 15, where: INSIDE,
    title: 'One failing test',
    action: 'Write a single test that fails right now and would pass if the problem were solved.',
    finish: 'A failing test exists.',
    bridge: 'Make it pass with the dumbest code possible, then clean up.',
    adapt: {
      smaller: { action: 'Write only the name of the test. Make it describe exactly what should happen.', mins: 2, effort: 1, finish: 'One precise test name.' },
    },
  }),
  stuck({
    id: 'c-duck', cats: ['code'], snags: ['broken', 'unsure'], flavor: 'perspective', family: 'explain-aloud',
    weird: 1, effort: 1, mins: 5, needs: ['talk'], where: INSIDE,
    title: 'Explain it to the duck',
    action: 'Pick any object on your desk. Explain the troubled code to it, line by line, out loud.',
    finish: "You've explained it all, or caught yourself saying 'wait...'.",
    bridge: "Go straight to the line where you said 'wait'.",
    adapt: {
      quiet: { action: 'Write a plain-English comment above every line of the troubled section, as if teaching someone new.', needs: [], finish: 'Every line has a comment.' },
    },
  }),
  stuck({
    id: 'c-trust-nothing', cats: ['code'], snags: ['broken'], flavor: 'squeeze', family: 'observe-state',
    weird: 1, effort: 1, mins: 10, where: INSIDE,
    title: 'Trust nothing',
    action: "Pick the three values you're surest about and print or log them. Assume nothing is what you think.",
    finish: "You've confirmed or disproved three assumptions.",
    bridge: 'Follow the first value that surprised you.',
  }),
  stuck({
    id: 'c-banned-keyword', cats: ['code'], snags: ['angle'], flavor: 'subtract', family: 'banned-construct',
    weird: 2, effort: 2, mins: 15, where: INSIDE,
    title: 'The banned keyword',
    action: "Rewrite the tangled part without a single 'if'. Use lookup tables, maps or small objects instead.",
    boundary: 'Scratch copy only. This is an experiment, not a rule for the real code.',
    finish: "The scratch version works, or you see why it can't.",
    bridge: 'Keep any structure that made the logic clearer. Throw away the rest.',
    adapt: {
      smaller: { action: "Find one 'if' in the tangled part and replace it with a lookup, on a scratch copy.", mins: 5, effort: 1, finish: 'One branch replaced.' },
    },
  }),
  stuck({
    id: 'c-from-memory', cats: ['code'], snags: ['broken', 'angle'], flavor: 'subtract', family: 'rewrite-memory',
    weird: 2, effort: 3, mins: 25, where: INSIDE,
    title: 'From memory',
    action: 'Close the file. Rewrite the troubled function from memory in a scratch file, without peeking.',
    finish: 'A from-memory version exists.',
    bridge: 'Compare the two. Where they differ is where your understanding and your code disagree.',
    adapt: {
      smaller: { action: "Without looking, write the function's steps as a numbered list. Then check it against the real code.", mins: 10, effort: 2, finish: 'A list of steps, checked against the code.' },
    },
  }),
  stuck({
    id: 'c-honest-names', cats: ['code'], snags: ['unsure', 'angle'], flavor: 'reframe', family: 'rename',
    weird: 1, effort: 1, mins: 10, where: INSIDE,
    title: 'Honest names',
    action: 'Rename the three vaguest variables or functions in the troubled area so each says exactly what it holds or does.',
    boundary: 'Rename only. No logic changes.',
    finish: 'Three honest names.',
    bridge: 'Re-read the code. Bugs often surface once things are named truthfully.',
  }),
  stuck({
    id: 'c-sentence-names', cats: ['code'], snags: ['angle', 'unsure'], flavor: 'substitute', family: 'silly-names',
    weird: 3, effort: 2, mins: 15, where: INSIDE,
    title: 'The sentence',
    action: 'Rename the variables in one function so that, read in order, they form a sentence.',
    boundary: 'Scratch copy only.',
    finish: 'The variables read as a sentence, however silly.',
    bridge: 'Did the story reveal what each value is really for? Bring back any name that is genuinely clearer.',
  }),
  stuck({
    id: 'c-smallest-commit', cats: ['code'], snags: ['finish', 'options'], flavor: 'squeeze', family: 'smallest-commit',
    weird: 1, effort: 1, mins: 10, where: INSIDE,
    title: 'Smallest commit',
    action: "Find the smallest piece of what you've done that works on its own, and commit it right now.",
    finish: 'One commit made.',
    bridge: 'Repeat with the next smallest working piece.',
  }),
  stuck({
    id: 'c-screen-off', cats: ['code'], snags: ['start', 'options'], flavor: 'substitute', family: 'paper-first',
    weird: 1, effort: 1, mins: 10,
    title: 'Screen off',
    action: 'Turn away from the screen. Draw the data flow on paper, with boxes for things and arrows for movement.',
    finish: 'A sketch from input to output.',
    bridge: 'Build the first box on the sketch.',
    adapt: {
      smaller: { action: 'On paper, draw just three boxes: what comes in, what happens, what comes out.', mins: 3, finish: 'Three boxes and two arrows.' },
    },
  }),
  stuck({
    id: 'c-whole-error', cats: ['code'], snags: ['broken'], flavor: 'reframe', family: 'read-error',
    weird: 1, effort: 1, mins: 5, where: INSIDE,
    title: 'Read the whole error',
    action: 'Read the full error word by word, including the parts you usually skip. Write down every file and line it mentions.',
    finish: "You've read every word and listed every location.",
    bridge: "Open the first location you haven't checked yet.",
  }),
  stuck({
    id: 'c-last-worked', cats: ['code'], snags: ['broken'], flavor: 'perspective', family: 'bisect',
    weird: 2, effort: 2, mins: 15, where: INSIDE,
    title: 'When did it last work?',
    action: 'Find the last version where this worked. Step through older versions until you find the change that broke it.',
    finish: "You've found the change, or narrowed it to a few.",
    bridge: 'Read that change slowly. The bug almost always lives there.',
  }),
  stuck({
    id: 'c-pirate-docs', cats: ['code'], snags: ['unsure', 'finish'], flavor: 'perspective', family: 'comment-voice',
    weird: 3, effort: 1, mins: 10, where: INSIDE,
    title: 'Pirate documentation',
    action: "Write comments for this module as a pirate captain explaining the ship's workings to new crew.",
    boundary: 'Scratch copy, or delete the pirate lines before committing.',
    finish: 'Every function has a pirate comment.',
    bridge: 'Rewrite the comments normally, keeping any explanation that became clearer.',
  }),
  stuck({
    id: 'c-cut-a-feature', cats: ['code'], snags: ['options', 'finish'], flavor: 'subtract', family: 'cut-scope',
    weird: 2, effort: 1, mins: 5,
    title: 'Cut a feature',
    action: "Pick one feature of what you're building and remove it from this version. Write it on a 'later' list.",
    finish: "One feature moved to 'later'.",
    bridge: 'Finish the smaller version first.',
  }),

  // ───────────────────────── Get unstuck: Writing ─────────────────────────
  stuck({
    id: 'w-wrong-opening', cats: ['writing'], snags: ['start'], flavor: 'invert', family: 'bad-opening',
    weird: 1, effort: 1, mins: 5,
    title: 'Write the wrong opening',
    action: 'In a scratch note, write three deliberately bad opening sentences. Pick the most interesting one and rewrite only that sentence.',
    finish: 'One usable first sentence.',
    bridge: 'Paste it at the top of your draft and keep going.',
    adapt: {
      smaller: { action: 'Write one bad opening sentence. Keep one phrase worth saving.', mins: 2, finish: 'One phrase worth saving.' },
    },
  }),
  stuck({
    id: 'w-start-at-end', cats: ['writing'], snags: ['start', 'finish'], flavor: 'invert', family: 'end-first',
    weird: 1, effort: 1, mins: 10,
    title: 'Start at the end',
    action: 'Write the last sentence first. Then write the sentence just before it.',
    finish: 'Two closing sentences.',
    bridge: "Now you know where you're going. Head there from the top.",
    adapt: {
      smaller: { action: 'Write only the very last sentence of the piece.', mins: 3, finish: 'One last sentence.' },
    },
  }),
  stuck({
    id: 'w-object-view', cats: ['writing'], snags: ['angle'], flavor: 'perspective', family: 'object-pov',
    weird: 2, effort: 2, mins: 15,
    title: "The object's view",
    action: 'Rewrite one paragraph from the point of view of an object in the scene, or in the room you are in.',
    finish: "One paragraph in the object's voice.",
    bridge: 'Steal one detail the object noticed that you had not.',
    adapt: {
      smaller: { action: 'Write three sentences the object would say about the situation.', mins: 5, effort: 1, finish: 'Three sentences in its voice.' },
    },
  }),
  stuck({
    id: 'w-small-words', cats: ['writing'], snags: ['angle', 'finish'], flavor: 'subtract', family: 'word-limit',
    weird: 3, effort: 2, mins: 10,
    title: 'Small words only',
    action: 'Rewrite one paragraph using only words of five letters or fewer.',
    boundary: 'Scratch copy only.',
    finish: 'One paragraph of short words.',
    bridge: 'Short words are often clearer. Bring back any line that got better.',
  }),
  stuck({
    id: 'w-vanished-letter', cats: ['writing'], snags: ['angle'], flavor: 'subtract', family: 'lipogram',
    weird: 3, effort: 2, mins: 15,
    title: 'The vanished letter',
    action: "Rewrite one paragraph without using the letter '{letter}'.",
    boundary: 'Scratch copy only.',
    finish: "One paragraph with no '{letter}' anywhere.",
    bridge: 'Look at the words you were forced to find. Keep any that are more vivid.',
    adapt: {
      smaller: { action: "Rewrite one sentence without the letter '{letter}'.", mins: 5, effort: 1, finish: "One sentence with no '{letter}'." },
    },
  }),
  stuck({
    id: 'w-bouncer', cats: ['writing'], snags: ['options'], flavor: 'subtract', family: 'keep-two',
    weird: 1, effort: 1, mins: 10,
    title: 'The bouncer',
    action: 'List all your ideas for this piece. Only two get in. Write one sentence on why each deserves it.',
    finish: 'Two ideas inside, the rest outside.',
    bridge: 'Write the next section using only those two.',
  }),
  stuck({
    id: 'w-dear-reader', cats: ['writing'], snags: ['unsure', 'start'], flavor: 'perspective', family: 'letter-reader',
    weird: 1, effort: 1, mins: 10,
    title: 'Dear reader',
    action: 'Write a short, informal letter to one specific reader, telling them what this piece is about and why it matters to them.',
    finish: 'A letter you could actually send.',
    bridge: 'Your best sentence from the letter probably belongs in the piece.',
  }),
  stuck({
    id: 'w-napkin', cats: ['writing'], snags: ['unsure', 'options'], flavor: 'squeeze', family: 'compress',
    weird: 1, effort: 1, mins: 5,
    title: 'Back of the napkin',
    action: 'Summarize the whole piece in 25 words or fewer.',
    finish: '25 words or fewer.',
    bridge: "Anything in your draft that doesn't serve those words is a candidate to cut.",
  }),
  stuck({
    id: 'w-read-aloud', cats: ['writing'], snags: ['finish', 'broken'], flavor: 'reframe', family: 'read-aloud',
    weird: 1, effort: 1, mins: 10, needs: ['talk'],
    title: 'Read it out loud',
    action: 'Read the troubled section aloud, slowly. Mark every place you stumble or get bored.',
    finish: 'Every stumble marked.',
    bridge: 'Fix the marks, starting with the first.',
    adapt: {
      quiet: { action: 'Read the section one line at a time, covering the rest. Mark every place your attention drifts.', needs: [] },
    },
  }),
  stuck({
    id: 'w-genre-swap', cats: ['writing'], snags: ['angle'], flavor: 'substitute', family: 'genre-swap',
    weird: 2, effort: 2, mins: 15,
    title: 'Genre swap',
    action: 'Rewrite one paragraph as {genre}.',
    boundary: 'Scratch copy only.',
    finish: 'One transformed paragraph.',
    bridge: 'Did the new genre force a clearer structure or a sharper image? Keep it.',
    adapt: {
      smaller: { action: 'Rewrite your opening sentence as {genre}.', mins: 5, effort: 1, finish: 'One transformed sentence.' },
    },
  }),
  stuck({
    id: 'w-trailer', cats: ['writing'], snags: ['angle', 'start'], flavor: 'substitute', family: 'genre-swap',
    weird: 3, effort: 1, mins: 10,
    title: 'Movie trailer',
    action: "Write your opening as the over-dramatic voice-over of a movie trailer. 'In a world where...'",
    finish: 'A trailer voice-over, as dramatic as possible.',
    bridge: 'Under the drama is the core tension of your piece. Name it in one plain sentence.',
    adapt: {
      weirder: { action: "Perform your opening out loud as a movie-trailer voice-over. 'In a world where...'", needs: ['talk'], finish: 'You performed it, however badly.' },
    },
  }),
  stuck({
    id: 'w-cut-ten', cats: ['writing'], snags: ['finish'], flavor: 'subtract', family: 'cut-percent',
    weird: 2, effort: 2, mins: 15,
    title: 'Cut ten percent',
    action: 'Cut ten percent of the words from the section you are stuck on. Every sentence earns its place or goes.',
    finish: 'The section is ten percent lighter.',
    bridge: 'Read it again. Usually it is done, or very close.',
    adapt: {
      smaller: { action: 'Cut one sentence that is only there because you worked hard on it.', mins: 3, effort: 1, finish: 'One sentence gone.' },
    },
  }),

  // ───────────────────────── Get unstuck: Design ─────────────────────────
  stuck({
    id: 'd-steal-a-shape', cats: ['design'], snags: ['angle'], flavor: 'substitute', family: 'borrow-shape',
    weird: 2, effort: 1, mins: 10, needs: ['move'], where: INSIDE,
    title: 'Steal from another room',
    action: 'Go to another room and pick one object. Borrow one shape or proportion from it and sketch a layout around it.',
    finish: 'One sketch built around a borrowed shape.',
    bridge: 'Does the shape belong in the real design? Keep it, or keep what it taught you.',
    adapt: {
      still: { action: 'Pick an object you can see from your seat. Borrow one shape or proportion and sketch a layout around it.', needs: [], where: ALL },
    },
  }),
  stuck({
    id: 'd-nearby-palette', cats: ['design'], snags: ['angle', 'options'], flavor: 'dice', family: 'near-palette',
    weird: 2, effort: 1, mins: 10,
    title: 'The nearby palette',
    action: 'Your palette is the three colors closest to your left hand. Mock up one screen or section using only those.',
    boundary: 'Scratch file only.',
    finish: 'A quick mockup in your three found colors.',
    bridge: 'Keep any pairing that surprised you.',
  }),
  stuck({
    id: 'd-two-sizes', cats: ['design'], snags: ['options', 'broken'], flavor: 'subtract', family: 'type-limit',
    weird: 1, effort: 2, mins: 15, where: INSIDE,
    title: 'Two sizes only',
    action: 'Redo the layout with two font sizes and one weight. Hierarchy has to come from space and position.',
    boundary: 'Duplicate first.',
    finish: 'A version with only two sizes.',
    bridge: 'Add back only the sizes that genuinely help.',
  }),
  stuck({
    id: 'd-lights-out', cats: ['design'], snags: ['broken', 'unsure'], flavor: 'subtract', family: 'remove-color',
    weird: 1, effort: 1, mins: 5, where: INSIDE,
    title: 'Lights out',
    action: 'View your design in grayscale. Note every place the hierarchy falls apart.',
    finish: 'A list of places that relied on color alone.',
    bridge: 'Fix the first one with size, weight or space.',
  }),
  stuck({
    id: 'd-three-in-ten', cats: ['design'], snags: ['start', 'angle'], flavor: 'squeeze', family: 'quick-variants',
    weird: 1, effort: 2, mins: 10,
    title: 'Three in ten',
    action: 'Sketch three wildly different layouts. Rough boxes only, no detail.',
    finish: 'Three sketches.',
    bridge: 'Pick the one that scares you a little and develop it for five minutes.',
    adapt: {
      smaller: { action: 'Sketch three layouts in three minutes. Boxes only.', mins: 3, effort: 1 },
    },
  }),
  stuck({
    id: 'd-upside-down', cats: ['design'], snags: ['broken', 'unsure'], flavor: 'perspective', family: 'fresh-eyes-flip',
    weird: 3, effort: 1, mins: 5, where: INSIDE,
    title: 'Turn it upside down',
    action: 'Flip your design upside down, or mirror it. Look at it as pure shapes for two minutes.',
    finish: "You've noticed at least one imbalance.",
    bridge: 'Fix that imbalance in the right-side-up version.',
  }),
  stuck({
    id: 'd-squint', cats: ['design'], snags: ['broken', 'finish'], flavor: 'perspective', family: 'fresh-eyes-flip',
    weird: 1, effort: 1, mins: 2, where: INSIDE,
    title: 'The squint test',
    action: 'Lean back and squint at your design until it blurs. What do you see first, second and third?',
    finish: 'You know what the eye hits first.',
    bridge: "If that's not the most important thing, change the design until it is.",
  }),
  stuck({
    id: 'd-one-word', cats: ['design'], snags: ['unsure', 'options'], flavor: 'reframe', family: 'design-word',
    weird: 1, effort: 1, mins: 5,
    title: 'One word',
    action: 'Choose one word this design should feel like. Check every element against it.',
    finish: 'One word chosen and every element judged.',
    bridge: 'Remove or change the element that fights the word hardest.',
  }),
  stuck({
    id: 'd-time-travel', cats: ['design'], snags: ['angle'], flavor: 'perspective', family: 'era-design',
    weird: 3, effort: 2, mins: 15,
    title: 'Time-travel brief',
    action: 'Redesign this as if it were made in {era}. Materials, ornament and attitude included.',
    boundary: 'Rough sketch, scratch file.',
    finish: 'One rough redesign from that era.',
    bridge: 'Bring back one detail that gives the real design more character.',
    adapt: {
      smaller: { action: 'Sketch just the header or title as if it were made in {era}.', mins: 5, effort: 1, finish: 'One small sketch.' },
    },
  }),
  stuck({
    id: 'd-remove-favorite', cats: ['design'], snags: ['finish', 'options'], flavor: 'subtract', family: 'remove-element',
    weird: 2, effort: 1, mins: 5, where: INSIDE,
    title: 'Remove your favorite',
    action: "Delete the element you're most attached to. See if the design still works.",
    boundary: 'Duplicate first. You can bring it back.',
    finish: 'The design, without your favorite element.',
    bridge: "If it still works, leave it out. If not, now you know exactly why it's needed.",
  }),
  stuck({
    id: 'd-copy-to-learn', cats: ['design'], snags: ['start'], flavor: 'substitute', family: 'study-master',
    weird: 1, effort: 2, mins: 15, where: INSIDE,
    title: 'Copy to learn',
    action: 'Find a design you admire and recreate a small part of it from scratch, purely as an exercise.',
    boundary: 'Practice only. Never ship the copy.',
    finish: 'One small part recreated.',
    bridge: 'Name one decision the original made that you had not considered.',
  }),

  // ───────────────────────── Get unstuck: Thinking & decisions ─────────────────────────
  stuck({
    id: 't-flip-for-it', cats: ['thinking'], snags: ['options'], flavor: 'dice', family: 'coin-reveal',
    weird: 2, effort: 1, mins: 2,
    title: 'Flip for it',
    action: 'Give your top two options to heads and tails. The grimoire flipped: {coin}. Notice your gut reaction before you argue with it.',
    finish: 'You know whether you felt relief or disappointment.',
    bridge: 'That feeling is data. Follow it, or find out why it disagrees with your head.',
  }),
  stuck({
    id: 't-wrong-on-purpose', cats: ['thinking'], snags: ['angle', 'unsure'], flavor: 'invert', family: 'assumption-flip',
    weird: 2, effort: 2, mins: 15,
    title: 'Wrong on purpose',
    action: 'List your three biggest assumptions. Imagine the biggest one is false, and sketch a plan for that world.',
    boundary: "A thought experiment. Don't act on it yet.",
    finish: 'A rough plan for the opposite world.',
    bridge: 'Is there a cheap way to test that assumption for real?',
    adapt: {
      smaller: { action: 'Write your single biggest assumption. Write one sentence on what changes if it is false.', mins: 5, effort: 1, finish: 'One assumption, flipped.' },
    },
  }),
  stuck({
    id: 't-ten-ten-ten', cats: ['thinking'], snags: ['options'], flavor: 'perspective', family: 'time-horizons',
    weird: 1, effort: 1, mins: 10,
    title: 'Ten, ten, ten',
    action: 'For each option, write how you will feel about it in ten minutes, ten months and ten years.',
    finish: 'Every option has three horizons.',
    bridge: 'Give the most weight to the horizon that matters most for this decision.',
  }),
  stuck({
    id: 't-advise-a-friend', cats: ['thinking'], snags: ['unsure', 'options'], flavor: 'perspective', family: 'advise-friend',
    weird: 1, effort: 1, mins: 5,
    title: 'Advise a friend',
    action: 'Imagine a friend brings you this exact situation. Write the advice you would give them.',
    finish: 'Three sentences of advice.',
    bridge: "Take your own advice, or write down why you won't.",
  }),
  stuck({
    id: 't-premortem', cats: ['thinking'], snags: ['options', 'finish'], flavor: 'invert', family: 'premortem',
    weird: 1, effort: 2, mins: 15,
    title: 'The pre-mortem',
    action: "It's six months from now and your plan failed badly. Write the story of why.",
    finish: 'A short failure story.',
    bridge: 'Fix the single most likely cause before you start.',
    adapt: {
      smaller: { action: 'Write the three most likely reasons your plan could fail.', mins: 5, effort: 1, finish: 'Three reasons.' },
    },
  }),
  stuck({
    id: 't-cheapest-test', cats: ['thinking'], snags: ['unsure', 'start'], flavor: 'squeeze', family: 'cheap-test',
    weird: 1, effort: 1, mins: 10,
    title: 'The cheapest test',
    action: 'What is the smallest, cheapest way to find out if you are right? Design it.',
    finish: 'A test you could run this week.',
    bridge: 'Put it in your calendar now.',
  }),
  stuck({
    id: 't-book-oracle', cats: ['thinking'], snags: ['angle', 'unsure'], flavor: 'dice', family: 'book-oracle',
    weird: 2, effort: 1, mins: 5,
    title: 'The book oracle',
    action: 'Open the nearest book to page {page}. Read the fifth sentence. How does it answer your question?',
    boundary: 'No book nearby? Use the nearest sentence you can see.',
    finish: 'You found an interpretation, however strange.',
    bridge: 'Write down what that interpretation suggests you do next.',
  }),
  stuck({
    id: 't-strange-council', cats: ['thinking'], snags: ['options', 'angle'], flavor: 'perspective', family: 'council',
    weird: 3, effort: 2, mins: 15,
    title: 'The strange council',
    action: 'Convene a council of a toddler, a pirate and a monk. Write what each advises about your decision.',
    finish: 'Three pieces of advice.',
    bridge: 'Which one annoyed you most? It may be the one you need.',
    adapt: {
      smaller: { action: 'Ask just the pirate. Write their advice in two lines.', mins: 3, effort: 1, finish: "The pirate's advice." },
    },
  }),
  stuck({
    id: 't-two-announcements', cats: ['thinking'], snags: ['options'], flavor: 'perspective', family: 'two-letters',
    weird: 2, effort: 2, mins: 15,
    title: 'Two announcements',
    action: 'Write a short note announcing each option as if you had already chosen it. Notice which one is easier to write.',
    finish: 'Both notes written.',
    bridge: 'The note that flowed is often your answer.',
  }),
  stuck({
    id: 't-elimination', cats: ['thinking'], snags: ['options'], flavor: 'subtract', family: 'eliminate',
    weird: 1, effort: 1, mins: 5,
    title: 'Elimination round',
    action: 'Eliminate one option right now, however hard. Write one line explaining why.',
    finish: 'One fewer option.',
    bridge: 'Repeat until two remain, then decide or sleep on it.',
  }),

  // ───────────────────────── Get unstuck: Learning ─────────────────────────
  stuck({
    id: 'l-five-sentences', cats: ['learning'], snags: ['unsure', 'finish'], flavor: 'perspective', family: 'teach',
    weird: 1, effort: 1, mins: 10,
    title: 'Teach it in five sentences',
    action: "Explain what you're learning to an imaginary student in exactly five sentences.",
    finish: 'Five sentences.',
    bridge: 'Where you hesitated is exactly what to review next.',
  }),
  stuck({
    id: 'l-no-words', cats: ['learning'], snags: ['angle', 'unsure'], flavor: 'substitute', family: 'draw-concept',
    weird: 2, effort: 2, mins: 10,
    title: 'No words allowed',
    action: 'Draw the concept with zero words. Shapes, arrows and doodles only.',
    finish: 'A wordless drawing.',
    bridge: 'Explain your drawing to yourself. Gaps in the explanation are gaps in understanding.',
  }),
  stuck({
    id: 'l-four-line-rap', cats: ['learning'], snags: ['angle', 'finish'], flavor: 'substitute', family: 'song-concept',
    weird: 3, effort: 2, mins: 10,
    title: 'Four-line rap',
    action: 'Turn the key idea into a four-line rap. Rhymes are mandatory. Quality is not.',
    finish: 'Four rhyming lines.',
    bridge: "Say it once more. You'll probably remember it tomorrow.",
  }),
  stuck({
    id: 'l-close-the-book', cats: ['learning'], snags: ['finish', 'unsure'], flavor: 'reframe', family: 'self-quiz',
    weird: 1, effort: 2, mins: 15,
    title: 'Close the book',
    action: 'Close everything and write down all you remember. Then check what you missed.',
    finish: 'A memory dump and a list of gaps.',
    bridge: 'Study only the gaps.',
    adapt: {
      smaller: { action: 'Close everything and write the three most important things you remember.', mins: 5, effort: 1, finish: 'Three things, checked.' },
    },
  }),
  stuck({
    id: 'l-questions-first', cats: ['learning'], snags: ['start'], flavor: 'reframe', family: 'questions-learn',
    weird: 1, effort: 1, mins: 5,
    title: 'Questions first',
    action: 'Before reading anything, write five questions you hope this topic answers.',
    finish: 'Five questions.',
    bridge: 'Read hunting for those answers.',
  }),
  stuck({
    id: 'l-analogy', cats: ['learning'], snags: ['angle', 'unsure'], flavor: 'substitute', family: 'analogy',
    weird: 2, effort: 1, mins: 10,
    title: 'Stretch the analogy',
    action: 'Explain the concept as if it were {analogy}. Push the comparison until it breaks.',
    finish: 'An analogy, stretched to breaking point.',
    bridge: 'Where it broke shows you what makes the concept unique.',
  }),
  stuck({
    id: 'l-tiniest-example', cats: ['learning'], snags: ['start', 'broken'], flavor: 'squeeze', family: 'tiny-example',
    weird: 1, effort: 2, mins: 15,
    title: 'Tiniest example',
    action: 'Build or solve the tiniest possible example of the idea. Strip away everything that is not essential.',
    finish: 'One tiny working example.',
    bridge: 'Add one complication at a time.',
  }),
  stuck({
    id: 'l-mistake-museum', cats: ['learning'], snags: ['broken'], flavor: 'reframe', family: 'error-log',
    weird: 1, effort: 1, mins: 10,
    title: 'Mistake museum',
    action: 'List the last three mistakes you made on this topic. For each, write the rule that would have prevented it.',
    finish: 'Three mistakes, three rules.',
    bridge: "Keep the rules where you'll see them next session.",
  }),
  stuck({
    id: 'l-walking-recall', cats: ['learning'], snags: ['finish', 'unsure'], flavor: 'body', family: 'walk-recall',
    weird: 2, effort: 2, mins: 15, needs: ['move', 'outside'], where: MOBILE,
    title: 'Walking recall',
    action: 'Go for a short walk and recall everything you know about the topic, step by step, in your head.',
    boundary: 'Up to fifteen minutes, on a route you know.',
    finish: "You've walked through the whole topic.",
    bridge: 'Note the first place your memory went blank. Start there.',
    adapt: {
      still: { action: 'Close your eyes and walk through the topic in your head, step by step, as if touring a building.', needs: [], where: ALL, mins: 10, effort: 1 },
    },
  }),
  stuck({
    id: 'l-alien', cats: ['learning'], snags: ['angle'], flavor: 'perspective', family: 'teach',
    weird: 3, effort: 1, mins: 10,
    title: 'Explain it to an alien',
    action: 'An alien has landed and urgently needs to understand this topic. They know nothing about Earth. Write your explanation.',
    finish: 'An explanation that assumes nothing.',
    bridge: 'Every Earth thing you had to explain was a hidden assumption. Check you really understand each one.',
  }),

  // ───────────────────────── Surprise me: make something ─────────────────────────
  bored({
    id: 'b-seven-objects', intents: ['make'], flavor: 'squeeze', family: 'object-sculpture',
    weird: 2, effort: 1, mins: 10, where: INSIDE,
    title: 'Seven-object sculpture',
    action: 'Build a tiny sculpture from exactly seven objects within reach. Give it a title.',
    finish: 'A sculpture with a title.',
    adapt: {
      smaller: { action: 'Balance three objects into a tiny tower and name it.', mins: 2, finish: 'A named tower.' },
    },
  }),
  bored({
    id: 'b-pocket-poem', intents: ['make'], flavor: 'dice', family: 'word-poem',
    weird: 1, effort: 1, mins: 5,
    title: 'Pocket poem',
    action: 'Write a four-line poem that includes the word {word}.',
    finish: 'Four lines.',
    adapt: {
      weirder: { action: 'Write a four-line poem from the point of view of a {word}.', weird: 2 },
    },
  }),
  bored({
    id: 'b-one-line', intents: ['make'], flavor: 'subtract', family: 'one-line',
    weird: 2, effort: 1, mins: 5,
    title: 'One unbroken line',
    action: 'Draw the object nearest to you without lifting your pen from the paper.',
    finish: 'One continuous-line drawing.',
    adapt: {
      weirder: { action: 'Draw your own face without lifting the pen and without looking at the paper.', weird: 3, finish: 'One gloriously strange self-portrait.' },
    },
  }),
  bored({
    id: 'b-six-words', intents: ['make'], flavor: 'squeeze', family: 'six-word',
    weird: 1, effort: 1, mins: 5,
    title: 'Six-word stories',
    action: 'Write a complete story in exactly six words. Then write two more.',
    finish: 'Three six-word stories.',
    adapt: {
      smaller: { action: 'Write one complete story in exactly six words.', mins: 2, finish: 'One six-word story.' },
    },
  }),
  bored({
    id: 'b-new-word', intents: ['make', 'play'], flavor: 'reframe', family: 'invent-word',
    weird: 2, effort: 1, mins: 5,
    title: 'Invent a word',
    action: "Invent a word for a feeling that doesn't have one yet. Write its definition and use it in a sentence.",
    finish: 'A new word, defined and used.',
  }),
  bored({
    id: 'b-fold-something', intents: ['make'], flavor: 'substitute', family: 'fold',
    weird: 1, effort: 1, mins: 10, where: INSIDE,
    title: 'Fold something',
    action: 'Take a sheet of paper and fold it into something: a boat, a cup, a creature. No instructions, just experiment.',
    finish: 'A folded thing, named.',
  }),
  bored({
    id: 'b-theme-tune', intents: ['make', 'play'], flavor: 'substitute', family: 'hum-theme',
    weird: 2, effort: 1, mins: 5, needs: ['sound'],
    title: 'Theme tune',
    action: 'Hum a theme tune for your day so far. Record it if you like.',
    finish: 'Your day has a theme.',
    adapt: {
      quiet: { action: 'Write the lyrics for a theme tune for your day so far. Four lines.', needs: [], finish: 'Four lines of theme tune.' },
    },
  }),
  bored({
    id: 'b-repeating-shapes', intents: ['make', 'explore'], flavor: 'perspective', family: 'repeat-shapes',
    weird: 1, effort: 2, mins: 10, needs: ['camera', 'move'], where: MOBILE,
    title: 'Repeating shapes',
    action: 'Find and photograph three repeating patterns around you.',
    finish: 'Three patterns captured.',
    adapt: {
      nocam: { action: 'Find three repeating patterns around you and sketch each one in a few lines.', needs: ['move'] },
      still: { action: 'Find three repeating patterns you can see without getting up. Sketch them.', needs: [], where: ALL, effort: 1 },
      smaller: { action: 'Find one repeating pattern and photograph it from an unusual angle.', mins: 3, effort: 1, finish: 'One pattern captured.' },
    },
  }),
  bored({
    id: 'b-found-palette', intents: ['make'], flavor: 'dice', family: 'color-palette',
    weird: 2, effort: 1, mins: 10,
    title: 'Found palette',
    action: 'Note the first five colors you see around you. Make anything using only those colors: a doodle, an outfit idea, a tiny poster.',
    finish: 'Something made from five found colors.',
  }),
  bored({
    id: 'b-letter-next-year', intents: ['make', 'reset'], flavor: 'perspective', family: 'future-letter',
    weird: 1, effort: 1, mins: 10,
    title: 'Letter to next year',
    action: "Write a short letter to yourself one year from now. Save it in a note titled with next year's date.",
    finish: 'A sealed letter, waiting a year.',
  }),

  bored({
    id: 'b-tiny-museum', intents: ['make', 'play'], flavor: 'reframe', family: 'museum-labels',
    weird: 3, effort: 1, mins: 10,
    title: 'Tiny museum',
    action: 'Curate a museum of three ordinary objects near you. Write a pompous museum label for each one.',
    finish: 'Three exhibits, three labels.',
    adapt: {
      smaller: { action: 'Pick one ordinary object and write its pompous museum label.', mins: 3, finish: 'One exhibit, labelled.' },
    },
  }),
  bored({
    id: 'b-drawer-creature', intents: ['make'], flavor: 'dice', family: 'drawer-creature',
    weird: 3, effort: 1, mins: 10,
    title: 'Drawer creature',
    action: 'Draw a creature built entirely from whatever is in the nearest drawer, bag or pocket. Give it a name and a habitat.',
    finish: 'A named creature with a home.',
  }),

  // ───────────────────────── Surprise me: explore ─────────────────────────
  bored({
    id: 'b-tourist-at-home', intents: ['explore', 'play'], flavor: 'perspective', family: 'tourist',
    weird: 3, effort: 1, mins: 5,
    title: 'Tourist at home',
    action: 'Be a tourist wherever you are. Find three "landmarks" and write a two-line guidebook entry for each.',
    finish: 'Three landmarks in your guidebook.',
  }),
  bored({
    id: 'b-ant-view', intents: ['explore'], flavor: 'perspective', family: 'ant-view',
    weird: 3, effort: 1, mins: 5, needs: ['move'],
    title: "Ant's-eye view",
    action: 'Get low, or hold your phone at floor level, and look around like an ant would. What looks enormous from down there?',
    finish: 'One enormous thing discovered.',
    adapt: {
      still: { action: 'Look at the nearest surface as if you were an ant crossing it. Describe the landscape in three sentences.', needs: [] },
    },
  }),
  bored({
    id: 'b-texture-collector', intents: ['explore'], flavor: 'body', family: 'texture-walk',
    weird: 1, effort: 2, mins: 10, needs: ['outside', 'move'], where: MOBILE,
    title: 'Texture collector',
    action: 'On a familiar, accessible route, collect unusual textures for up to ten minutes. Touch them where it is safe.',
    finish: 'At least five textures noticed.',
    adapt: {
      indoors: { action: 'Collect five unusual textures inside your home. Touch each one and describe it in a word.', needs: ['move'], where: ['home'] },
      smaller: { action: 'Find one surprising texture within ten steps of where you are.', mins: 2, effort: 1, needs: ['move'], where: ALL, finish: 'One texture found.' },
    },
  }),
  bored({
    id: 'b-color-angle', intents: ['explore'], flavor: 'dice', family: 'color-hunt',
    weird: 2, effort: 2, mins: 10, needs: ['move', 'camera'], where: MOBILE,
    title: 'Something {color}',
    action: 'Within ten minutes, find something {color}. Photograph it from an angle nobody would choose.',
    finish: 'One strange-angle photo of something {color}.',
    adapt: {
      nocam: { action: 'Within ten minutes, find something {color}. Sketch it from an angle nobody would choose.', needs: ['move'], finish: 'One strange-angle sketch.' },
      still: { action: 'Find something {color} you can see from where you are. Describe it as if you had never seen one before.', needs: [], where: ALL, mins: 5, effort: 1, finish: 'A fresh description.' },
    },
  }),
  bored({
    id: 'b-rabbit-hole', intents: ['explore'], flavor: 'dice', family: 'rabbit-hole',
    weird: 1, effort: 1, mins: 15,
    title: 'Rabbit hole',
    action: 'Look up {topic}. Follow three links or references deeper. Note the strangest fact you find.',
    finish: 'One strange fact, written down.',
    adapt: {
      smaller: { action: 'Look up {topic} and find one surprising fact.', mins: 5 },
    },
  }),
  bored({
    id: 'b-object-history', intents: ['explore'], flavor: 'perspective', family: 'object-curiosity',
    weird: 1, effort: 1, mins: 5,
    title: 'The thing to your right',
    action: 'Learn one real fact about the object directly to your right: how it is made, where it came from, or who invented it.',
    finish: 'One new fact about an ordinary thing.',
  }),
  bored({
    id: 'b-sound-layers', intents: ['explore', 'reset'], flavor: 'perspective', family: 'sound-layers',
    weird: 1, effort: 1, mins: 5,
    title: 'Sound layers',
    action: 'Close your eyes and count every distinct sound you can hear. Try to reach ten.',
    finish: 'As many sounds as you could find.',
  }),
  bored({
    id: 'b-invent-stranger', intents: ['explore', 'make'], flavor: 'perspective', family: 'stranger-story',
    weird: 2, effort: 1, mins: 10,
    title: 'Invent a backstory',
    action: 'Pick a passing car, bird, or the building across the street. Invent its full backstory.',
    finish: 'A backstory with at least one secret.',
  }),
  bored({
    id: 'b-clockwork-walk', intents: ['explore'], flavor: 'dice', family: 'map-wander',
    weird: 2, effort: 2, mins: 25, needs: ['outside', 'move'], where: MOBILE,
    title: 'Clockwork walk',
    action: 'Walk familiar streets. At each junction, check the minute: even means turn left, odd means turn right. Head home after {num} turns.',
    boundary: 'Stay on streets you know and feel safe on.',
    finish: '{num} turns taken, and you are back.',
    adapt: {
      indoors: { action: 'Wander your home and let the clock pick each doorway: even minute, left; odd minute, right. Notice one thing you had never noticed.', needs: ['move'], where: ['home'], mins: 5, effort: 1, finish: 'One thing newly noticed.' },
    },
  }),
  bored({
    id: 'b-photo-archaeology', intents: ['explore', 'reset'], flavor: 'dice', family: 'memory-photo',
    weird: 1, effort: 1, mins: 5,
    title: 'Photo archaeology',
    action: 'Find a photo in your gallery from {num} years ago, or as close as you can get. Remember one detail the photo does not show.',
    finish: 'One remembered detail.',
  }),
  bored({
    id: 'b-word-abroad', intents: ['explore'], flavor: 'dice', family: 'new-language',
    weird: 1, effort: 1, mins: 5,
    title: 'A word abroad',
    action: "Learn how to say '{word}' in a language you don't speak. Use it in a sentence today.",
    finish: 'A new word in your pocket.',
  }),

  // ───────────────────────── Surprise me: reset ─────────────────────────
  bored({
    id: 'b-blind-tasting', intents: ['reset'], flavor: 'body', family: 'mindful-taste',
    weird: 1, effort: 1, mins: 5,
    title: 'Blind tasting',
    action: "Eat or drink something with your eyes closed. Describe it in three words you wouldn't normally use.",
    finish: 'Three unusual words.',
  }),
  bored({
    id: 'b-square-breathing', intents: ['reset'], flavor: 'body', family: 'breath',
    weird: 1, effort: 1, mins: 2,
    title: 'Square breathing',
    action: 'Breathe in for four counts, hold for four, out for four, hold for four. Repeat four times.',
    finish: 'Four slow squares.',
  }),
  bored({
    id: 'b-reach-ceiling', intents: ['reset'], flavor: 'body', family: 'stretch',
    weird: 1, effort: 1, mins: 2, needs: ['move'],
    title: 'Reach for the ceiling',
    action: 'Stand up and stretch toward the ceiling, then slowly fold toward the floor. Repeat three times.',
    finish: 'Three slow stretches.',
    adapt: {
      still: { action: 'Roll your shoulders back five times, then gently turn your head left and right.', needs: [], finish: 'Shoulders and neck, loosened.' },
    },
  }),
  bored({
    id: 'b-five-four-three', intents: ['reset'], flavor: 'perspective', family: 'senses-ground',
    weird: 1, effort: 1, mins: 5,
    title: 'Five, four, three',
    action: 'Notice five things you can see, four you can touch, three you can hear, two you can smell and one you can taste.',
    finish: 'All fifteen noticed.',
  }),
  bored({
    id: 'b-one-small-order', intents: ['reset', 'make'], flavor: 'squeeze', family: 'tiny-tidy',
    weird: 1, effort: 1, mins: 5, where: INSIDE,
    title: 'One small order',
    action: 'Tidy one tiny area, like a drawer or a corner of your desk. Stop when the time is up.',
    finish: 'One small area in order.',
  }),
  bored({
    id: 'b-odd-thanks', intents: ['reset'], flavor: 'reframe', family: 'odd-gratitude',
    weird: 2, effort: 1, mins: 5,
    title: 'Odd thanks',
    action: 'Write thank-you notes to three objects that quietly helped you today.',
    finish: 'Three objects, thanked.',
  }),
  bored({
    id: 'b-sky-check', intents: ['reset', 'explore'], flavor: 'perspective', family: 'sky-watch',
    weird: 1, effort: 1, mins: 5,
    title: 'Sky check',
    action: 'Look at the sky for five minutes, through a window if you need to. Find one shape in it.',
    finish: 'One shape found.',
  }),
  bored({
    id: 'b-slow-motion', intents: ['reset', 'play'], flavor: 'body', family: 'slow-motion',
    weird: 3, effort: 1, mins: 2, needs: ['move'],
    title: 'Slow motion',
    action: 'Do your next ordinary action, like standing up or drinking water, in extreme slow motion. Take a full minute.',
    finish: 'One very slow minute.',
    adapt: {
      still: { action: 'Raise one hand to your face in extreme slow motion. Take a full minute.', needs: [] },
    },
  }),

  bored({
    id: 'b-shake-it-out', intents: ['reset', 'play'], flavor: 'body', family: 'shake-out',
    weird: 3, effort: 1, mins: 2, needs: ['move'],
    title: 'Shake it out',
    action: 'Shake each arm and each leg for ten seconds, like a dog drying off.',
    finish: 'Every limb shaken.',
    adapt: {
      still: { action: 'Shake out your hands for twenty seconds, then let them rest in your lap.', needs: [], finish: 'Hands shaken and resting.' },
    },
  }),
  bored({
    id: 'b-long-note', intents: ['reset'], flavor: 'body', family: 'long-exhale',
    weird: 2, effort: 1, mins: 2, needs: ['sound'],
    title: 'One long note',
    action: 'Hum one low note for as long as your breath lasts. Do it three times.',
    finish: 'Three long notes.',
    adapt: {
      quiet: { action: 'Breathe out as slowly as you can, as if fogging a mirror. Do it five times.', needs: [], finish: 'Five slow breaths out.' },
    },
  }),
  bored({
    id: 'b-rename-day', intents: ['reset', 'make'], flavor: 'reframe', family: 'chapter-title',
    weird: 2, effort: 1, mins: 5,
    title: 'Chapter title',
    action: 'Give today so far a title, like a chapter in a novel. Then write a better title for the rest of today.',
    finish: 'Two chapter titles.',
  }),

  // ───────────────────────── Surprise me: play (appears under Anything) ─────────────────────────
  bored({
    id: 'b-questions-only', intents: ['play'], flavor: 'invert', family: 'speak-questions',
    weird: 3, effort: 1, mins: 10, needs: ['talk'],
    title: 'Questions only',
    action: 'For the next ten minutes, speak only in questions. Even to yourself.',
    finish: 'Ten minutes of nothing but questions.',
    adapt: {
      quiet: { action: 'For the next ten minutes, write your thoughts only as questions.', needs: [] },
      smaller: { action: 'For the next two minutes, speak only in questions.', mins: 2, finish: 'Two minutes of questions.' },
    },
  }),
  bored({
    id: 'b-documentary', intents: ['play'], flavor: 'perspective', family: 'narrate',
    weird: 3, effort: 1, mins: 5, needs: ['talk'],
    title: 'Nature documentary',
    action: 'Narrate what you are doing in the hushed voice of a wildlife documentary.',
    finish: 'Five minutes of narration.',
    adapt: {
      quiet: { action: 'Write a nature-documentary narration of the last five minutes of your life.', needs: [], finish: 'One documentary script.' },
    },
  }),
  bored({
    id: 'b-other-hand', intents: ['play', 'make'], flavor: 'substitute', family: 'other-hand',
    weird: 2, effort: 1, mins: 5,
    title: 'The other hand',
    action: 'Write or draw something with your non-dominant hand: a grocery list, a self-portrait, anything.',
    finish: 'One wobbly masterpiece.',
  }),
  bored({
    id: 'b-alphabet-hunt', intents: ['play', 'explore'], flavor: 'dice', family: 'alphabet-hunt',
    weird: 2, effort: 1, mins: 5,
    title: 'Alphabet hunt',
    action: 'Find something around you for every letter, starting from {alpha}. How far can you get?',
    finish: 'As far through the alphabet as you got.',
  }),
  bored({
    id: 'b-backwards-plan', intents: ['play'], flavor: 'invert', family: 'reverse-routine',
    weird: 2, effort: 1, mins: 5,
    title: 'Backwards day',
    action: 'Write your plan for the rest of today in reverse order, from bedtime back to now. See if the order makes more sense.',
    finish: 'A backwards plan.',
  }),
  bored({
    id: 'b-interview-object', intents: ['play'], flavor: 'perspective', family: 'object-pov',
    weird: 3, effort: 1, mins: 5,
    title: 'Interview an object',
    action: 'Interview the nearest object. Write five questions and the answers it would give.',
    finish: 'A five-question interview.',
  }),
  bored({
    id: 'b-five-emoji', intents: ['play', 'make'], flavor: 'squeeze', family: 'emoji-story',
    weird: 2, effort: 1, mins: 2,
    title: 'Day in five',
    action: 'Tell the story of your day so far in exactly five emoji. Then write the caption.',
    finish: 'Five emoji and a caption.',
  }),
  bored({
    id: 'b-house-rule', intents: ['play'], flavor: 'dice', family: 'random-rule',
    weird: 3, effort: 1, mins: 15,
    title: 'House rule',
    action: 'Until the time is up, every time you reach for your phone, first name three things that are {color}.',
    finish: 'The rule held until the end.',
    adapt: {
      smaller: { action: 'For five minutes, every time you reach for your phone, first name three things that are {color}.', mins: 5 },
    },
  }),
];
